name: 'CSV Lint'

on:
  pull_request:
    branches: 
      - 'main'
      - 'add-csvlinting'
  workflow_dispatch:

jobs:
  csvlinter:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v3
    - name: csvlinter
      uses: kcheriyath/csvlinter@V0.6.0
      with:
        find_pattern: "*.csv"

  csvvalidator:
    name: csv schematic validate
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.9'

      - name: Install Schematic
        shell: bash
        run: |
          pip3 install poetry
          git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
          cd schematic
          poetry build
          pip3 install dist/schematicpy-*-py3-none-any.whl

      
      - name: Convert CSV schema
        shell: bash
        run: |
          schematic schema convert .github/CSV.model.csv   

      - name: Validate data model CSV
        shell: bash
        run: |
          schematic model -c .github/CSV_schematic_config.yml validate -mp HTAN.model.csv -dt "DataModel"