# This workflow is used to convert changed HTAN.model.csv to HTAN.model.jsonld
# and push the updated HTAN.model.jsonld to feature branch

name: CI

on:
  pull_request:
    branches: main
    paths: 'HTAN.model.csv'

jobs:
  CI:
    name: schema-convert
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.9'

      - name: Install Schematic
        shell: bash
        run: |
          echo Installing pypi version of schematic
          git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
          cp schematic_config.yml schematic/config.yml
          cd schematic
          pip3 install schematicpy

      - name: Convert .csv to .jsonld
        shell: bash
        run: |
          schematic schema convert HTAN.model.csv

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit the changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add HTAN.model.jsonld
          git commit -m "GitHub Action: convert *.model.csv to *.model.jsonld" || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
