name: 'CSV Lint'

on:
  pull_request:
    branches: 
      - 'main'
      - 'add-csvlinting'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v3
    - name: csvlinter
      uses: kcheriyath/csvlinter@V0.6.0
      with:
        find_pattern: "*.csv"
