name: Perform model integrity checks

on:
  pull_request:
    branches: 'main'
    paths: 'HTAN.model.csv'
  workflow_dispatch:

concurrency:
# cancel the current running workflow from the same branch, PR when a new workflow is triggered
# when the trigger is not a PR but a push, it will use the commit sha to generate the concurrency group
# {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
# {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag
# {{ github.sha }}: full commit sha
# credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.sha }}
  cancel-in-progress: true

jobs:
  component_requirements_check:
    name: Check component requirements
    if: always()
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas

      - name: Run script
        shell: bash
        run: |
          python .github/workflows/check_components.py

  attributes_exist_check:
    name: Check attributes exist
    if: always()
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas

      - name: Run script
        shell: bash
        run: |
          python .github/workflows/check_attributes_exist.py

  attributes_used_check:
    name: Check attributes are used
    if: always()
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas

      - name: Run script
        shell: bash
        run: |
          python .github/workflows/check_attributes_are_used.py

  attributes_unique_check:
    name: Check attributes are unique
    if: always()
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas

      - name: Run script
        shell: bash
        run: |
          python .github/workflows/check_attributes_are_unique.py