on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    name: Move issue to not planned
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ADD_TO_PROJECT_PAT }}"
        project-url: "https://github.com/orgs/github/projects/4"
        column-name: "Not planned"
        label-name: "notplanned"
